id: I9658BC87
initial_creation_type: ebook
source_metadata:
  id: MIN-LC-001
  title: གཏེར་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་རྣམ་ཐར་དད་པའི་ཤིང་རྟ་ཞེས་བྱ་བ་ཞུགས་སོ།
  author: མཛད་པ་པོ། ལོ་ཆེན་དྷརྨ་ཤྲཱི། ངག་དབང་ཆོས་དཔལ་རྒྱ་མཚོ།
  authors: &id001
  - མཛད་པ་པོ། ལོ་ཆེན་དྷརྨ་ཤྲཱི། ངག་དབང་ཆོས་དཔལ་རྒྱ་མཚོ།
  sku: MIN-LC-001
  cover: MIN-LC-001.jpg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: གཏེར་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་རྣམ་ཐར་དད་པའི་ཤིང་རྟ་ཞེས་བྱ་བ་ཞུགས་སོ།
  authors: *id001
  sku: MIN-LC-001
  cover: MIN-LC-001.jpg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
